apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-certificate
  namespace: apps
spec:
  secretName: client-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  commonName: 'http mtls demo'
  usages:
    - client auth
    - key encipherment
    - digital signature
  issuerRef:
    name: root-issuer
    kind: Issuer
