apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-certificate
  namespace: default
spec:
  isCA: true
  secretName: root-certificate
  commonName: "Root Certificate"
  privateKey:
    algorithm: RSA
    size: 4096
    encoding: PKCS8
  issuerRef:
    name: bootstrap-issuer
    kind: Issuer