apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-mtls
spec:
  selector:
    matchLabels:
      app: http-mtls
  template:
    metadata:
      labels:
        app: http-mtls
    spec:
      volumes:
        - name: certs
          secret:
            secretName: server-certificate
      containers:
        - name: http-mtls
          image: izaakdale/http-mtls
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /certs
              name: certs
          env:
            - name: PORT
              value: '443'
            - name: ENABLE_TLS
              value: 'true'
            - name: SERVER_CRT
              value: '/certs/tls.crt'
            - name: SERVER_KEY
              value: '/certs/tls.key'
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 443
