apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-certificate
  namespace: apps
spec:
  secretName: server-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  commonName: 'http mtls demo'
  dnsNames:
    - 'http-mtls-service'
  usages:
    - server auth
    - key encipherment
    - digital signature
  issuerRef:
    name: root-issuer
    kind: Issuer
